# Generated by Django 4.2.11 on 2024-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_remove_receiveddata_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveddata',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
