# Generated by Django 4.2.11 on 2024-04-16 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_receiveddata_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveddata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='receiveddata',
            name='version',
        ),
        migrations.RemoveField(
            model_name='token',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='receiveddata',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='receiveddata',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='generator.token'),
        ),
    ]
