# Generated by Django 4.2.11 on 2024-04-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_remove_receiveddata_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='generator.token')),
            ],
        ),
        migrations.DeleteModel(
            name='ReceivedData',
        ),
    ]
