# Generated by Django 4.2.11 on 2024-04-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_receiveddata_token_created_at_delete_storageitem_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='receiveddata',
            unique_together={('key', 'token')},
        ),
    ]
